### ISSUE TITLE
Instructions for installation on server are unclear

### ISSUE THREAD

**Issue by ubuntupunk** [PayFast/mod-zencart_1_3#1]
Hi there, I need to ask you how you which parts to place where. includes >> includes, admin >> admin?The instructions are very unclear as to how exactly to about installing this on the server.

**Comment by appinlet** [comment]
Hi @ubuntupunk 

Copy and paste all files from the root of this repository into the root of your Zen Cart installation. The one exception is the contents of the extracted 'admin' folder, which should match the directory name of your ZenCart admin URL (as this may have been renamed during the ZenCart install process).
